# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

#Change Port to 8080
EXPOSE 8080

# Labels consumed by OpenShift

LABEL io.k8s.description="A basic Apache HTTP Server child image, use ONBUILD" \
  io.k8s.displayname="Apache HTTP Server" \
  io.opensift.expose-services="8080:http" \
  io.openshift.tags="apache,httpd"

# Change Apache Config to listen on 8080
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf

# Change container to allow it to run on Openshift
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
  chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001
